-- Insert all requested hubs
INSERT INTO public.hubs (name) VALUES
  ('AECOM'),
  ('Aldeafuente'),
  ('Babel'),
  ('Banco Santander'),
  ('BBVA'),
  ('Brains Alcobendas'),
  ('Brains Arturo Soria'),
  ('Cisco'),
  ('Dell'),
  ('ETSII'),
  ('Fuenllana'),
  ('GFT'),
  ('Ikea'),
  ('Inditex'),
  ('Knowmad mood'),
  ('Legamar'),
  ('Logos'),
  ('Mas Orange'),
  ('Moeve'),
  ('NTT Datta'),
  ('Repsol'),
  ('Securitas'),
  ('Siemens'),
  ('UC3M'),
  ('Verisure');