// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orvkqnbshkxzyhqpjsdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ydmtxbmJzaGt4enlocXBqc2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NTA0NTgsImV4cCI6MjA4NDEyNjQ1OH0.Mdb2h5UejjiCClh2IN_VRFyl1PPMT4oAHfiasHWcsJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});